import { Card } from "@/game-engine/types";

export const cards: Card[] = [
  { id: 1, text: "Um de nos, secretamente, deseja a morte dos outros. Quem?" },
  { id: 2, text: "Acabamos de descobrir um baita segredo! Quem e o primeiro a conta-lo?" },
  { id: 3, text: "Um de nos tem o fetiche de comer coco. Quem?" },
  { id: 4, text: "Um de nos acredita que o mundo seria melhor se nao tivesse saude publica. Quem?" },
  { id: 5, text: "Um de nos, secretamente, admira Hitler. Quem?" },
  { id: 6, text: "Quem odeia a propria vida?" },
  { id: 7, text: "Alugamos uma casa de praia e esta tudo certo pra viagem. Quem fura no ultimo minuto e deixa todos na mao?" },
  { id: 8, text: "Quem pede dinheiro emprestado sabendo que nunca vai devolver?" },
  { id: 9, text: "Se todos fossemos presidentes de um pais, quem seria o primeiro a impor a pena de morte?" },
  { id: 10, text: "Voce esta em uma situacao complicada. Para qual de nos voce NAO pede conselho?" },
  { id: 11, text: "Somos candidatos a presidente. Quem recebe menos votos?" },
  { id: 12, text: "Um de nos tem uma vida dupla. Quem?" },
  { id: 13, text: "Estamos todos em quarentena, contagiados por um virus mortal e incuravel. Quem ira escapar e gerar uma epidemia?" },
  { id: 14, text: "Todos temos medo quando o motorista da vez e..." },
  { id: 15, text: "Voce finge que esta dormindo para nao ter que conversar com a pessoa do seu lado. Quem e essa pessoa?" },
  { id: 16, text: "Estamos em um aviao sem controle e achamos paraquedas pra todos, menos pra um. Quem e o primeiro a pegar um paraquedas e se salvar?" },
  { id: 17, text: "Viajamos todos para Las Vegas. Quem volta casado?" },
  { id: 18, text: "Nos eramos apostolos. Quem era Judas?" },
  { id: 19, text: "Cada um publica um livro com sua propria autobiografia. Qual te interessa menos?" },
  { id: 20, text: "Um de nos nunca mais podera te abracar. Quem?" },
  { id: 21, text: "Somos parte de um grupo de foragidos procurados no Velho Oeste. A cabeca de quem vale menos?" },
  { id: 22, text: "Precisamos de alguem para comandar as nossas tropas. Por favor, que nao seja..." },
  { id: 23, text: "Se todos decidirmos virar comediantes, quem e o primeiro a morrer de fome?" },
  { id: 24, text: "Em futuro proximo, um de nos ira morrer sendo vitima de um acerto de contas. Quem?" },
  { id: 25, text: "Quem se acha mais inteligente do que realmente e?" },
  { id: 26, text: "Acordamos em uma ilha deserta e sem nenhum alimento. Quem ira propor canibalismo?" },
  { id: 27, text: "Qual de nos voce jamais se atreveria a deixar irritado?" },
  { id: 28, text: "Estamos na prisao. Quem e o primeiro a se prostituir em troca de protecao?" },
  { id: 29, text: "Fomos convidados ao programa do Silvio. Quem discute com ele?" },
  { id: 30, text: "Quem se acha melhor do que os outros?" },
  { id: 31, text: "Vossa Majestade Infernal, tambem conhecido como Satanas, propoe realizar todos os nossos desejos em troca de nossas almas. Quem e o primeiro a aceitar?" },
  { id: 32, text: "Ganharemos mil dolares pra cada colher de merda que comermos. Quem esta mais disposto a ser rico?" },
  { id: 33, text: "Quem pede o prato mais caro do cardapio e se faz de sonso na hora de dividir a conta?" },
  { id: 34, text: "Jamais encostaria na roupa intima de..." },
  { id: 35, text: "O servico militar agora e obrigatorio para todos e todas. Quem e o primeiro a atirar no proprio pe para nao servir?" },
  { id: 36, text: "Quem le a Biblia?" },
  { id: 37, text: "Todo grupo de amigos tem aquele que se veste muito mal. Em nosso grupo e..." },
  { id: 38, text: "Estamos no Apocalipse Zumbi! Quem e o primeiro a morrer?" },
  { id: 39, text: "Trabalhamos em um restaurante de fast food. Quem cospe na comida?" },
  { id: 40, text: "Um de nos e, na realidade, um robo. Quem?" },
  { id: 41, text: "Qual de nos voce NAO escolheria para adotar o seu filho?" },
  { id: 42, text: "\"Acho certo que o Brasil permita o casamento entre duas pessoas do mesmo genero\" todos pensam, menos..." },
  { id: 43, text: "Quem peidou?" },
  { id: 44, text: "Quem convidaria um ex para tomar um cafe e mentiria descaradamente sobre sua vida atual?" },
  { id: 45, text: "Estamos participando de um reality show de talentos. Quem e eliminado no primeiro capitulo?" },
  { id: 46, text: "Um de nos tem uma colecao de chicletes mastigados pelo ex. Quem?" },
  { id: 47, text: "Um de nos nao ve graca nesse jogo, mas esta rindo apenas pra fingir que nao e um cuzao. Quem?" },
  { id: 48, text: "Um de nos finge que esta de boa, mas esta secretamente ressentido pelo resultado de uma carta. Quem?" },
  { id: 49, text: "Descobriram a formula da imortalidade. Para o bem da humanidade, voce esconde a formula de quem?" },
  { id: 50, text: "Um amigo em comum necessita de doacao de sangue. Quem disse que doou, mas nem apareceu?" },
  { id: 51, text: "Um de nos gosta de sentir o proprio cheiro de chule. Quem?" },
  { id: 52, text: "Estamos em um apocalipse nuclear. Quem roubaria os suprimentos de comida escondido?" },
  { id: 53, text: "Quem e o mais provavel de esquecer o aniversario de todos?" },
  { id: 54, text: "Um de nos tem vergonha dos proprios pais. Quem?" },
  { id: 55, text: "Quem seria o primeiro a vender um amigo por dinheiro?" },
  { id: 56, text: "Quem ja stalkeou o ex nas redes sociais usando conta fake?" },
  { id: 57, text: "Um de nos tem medo irracional de pombo. Quem?" },
  { id: 58, text: "Quem e o mais provavel de dar bolo e inventar desculpa esfarrapada?" },
  { id: 59, text: "Quem trocaria um amigo por um influenciador famoso?" },
  { id: 60, text: "Um de nos ainda manda mensagem para \"crush\" que nao responde. Quem?" },
  { id: 61, text: "Quem faria pacto com entidade sobrenatural em troca de fama?" },
  { id: 62, text: "Um de nos tem playlist secreta so com musica brega. Quem?" },
  { id: 63, text: "Quem ja fingiu nao ver alguem na rua para nao ter que cumprimentar?" },
  { id: 64, text: "Um de nos ja chorou vendo comercial de TV. Quem?" },
  { id: 65, text: "Quem seria o primeiro a rir num velorio em momento inadequado?" },
  { id: 66, text: "Um de nos tem colecao bizarra escondida em casa. Quem?" },
  { id: 67, text: "Quem e mais provavel de virar coach picareta?" },
  { id: 68, text: "Um de nos ja fucou o celular de outra pessoa escondido. Quem?" },
  { id: 69, text: "Quem terminaria relacionamento por mensagem de texto?" },
  { id: 70, text: "Um de nos ainda sente ciume de relacionamento antigo. Quem?" },
  { id: 71, text: "Quem toparia participar de experimento cientifico perigoso em troca de dinheiro?" },
  { id: 72, text: "Um de nos mente sobre quantas pessoas ja beijou. Quem?" },
  { id: 73, text: "Quem inventaria fake news so para ver a confusao?" },
  { id: 74, text: "Um de nos marcaria casamento so para ganhar presente. Quem?" },
  { id: 75, text: "Quem seria o primeiro a abandonar o grupo no meio de um perrengue?" },
  { id: 76, text: "Um de nos ja desejou o termino do relacionamento de outra pessoa. Quem?" },
  { id: 77, text: "Quem toparia viver em reality show 24 horas por dia?" },
  { id: 78, text: "Um de nos guarda rancor por coisa pequena ha anos. Quem?" },
  { id: 79, text: "Quem seria cancelado na internet em menos de uma semana?" },
  { id: 80, text: "Um de nos tem fantasias estranhas com professor(a) do passado. Quem?" },
  { id: 81, text: "Quem trocaria voto por favor pessoal?" },
  { id: 82, text: "Um de nos ainda conversa com \"contatinho\" enquanto esta em relacionamento serio. Quem?" },
  { id: 83, text: "Quem e mais provavel de inventar doenca para faltar a compromisso?" },
  { id: 84, text: "Um de nos desligaria o Wi-Fi da casa inteira para ter paz. Quem?" },
];
