import { Card } from "@/game-engine/types";

export const cards: Card[] = [
  { id: 1, text: "Um de nós, secretamente, deseja a morte dos outros. Quem?" },
  { id: 2, text: "Acabamos de descobrir um baita segredo! Quem é o primeiro a contá-lo?" },
  { id: 3, text: "Um de nós tem o fetiche de comer cocô. Quem?" },
  { id: 4, text: "Um de nós acredita que o mundo seria melhor se não tivesse saúde pública. Quem?" },
  { id: 5, text: "Um de nós, secretamente, admira Hitler. Quem?" },
  { id: 6, text: "Quem odeia a própria vida?" },
  { id: 7, text: "Alugamos uma casa de praia e está tudo certo pra viagem. Quem fura no último minuto e deixa todos na mão?" },
  { id: 8, text: "Quem pede dinheiro emprestado sabendo que nunca vai devolver?" },
  { id: 9, text: "Se todos fôssemos presidentes de um país, quem seria o primeiro a impor a pena de morte?" },
  { id: 10, text: "Você está em uma situação complicada. Para qual de nós você NÃO pede conselho?" },
  { id: 11, text: "Somos candidatos a presidente. Quem recebe menos votos?" },
  { id: 12, text: "Um de nós tem uma vida dupla. Quem?" },
  { id: 13, text: "Estamos todos em quarentena, contagiados por um vírus mortal e incurável. Quem irá escapar e gerar uma epidemia?" },
  { id: 14, text: "Todos temos medo quando o motorista da vez é..." },
  { id: 15, text: "Você finge que está dormindo para não ter que conversar com a pessoa do seu lado. Quem é essa pessoa?" },
  { id: 16, text: "Estamos em um avião sem controle e achamos paraquedas pra todos, menos pra um. Quem é o primeiro a pegar um paraquedas e se salvar?" },
  { id: 17, text: "Viajamos todos para Las Vegas. Quem volta casado?" },
  { id: 18, text: "Nós éramos apóstolos. Quem era Judas?" },
  { id: 19, text: "Cada um publica um livro com sua própria autobiografia. Qual te interessa menos?" },
  { id: 20, text: "Um de nós nunca mais poderá te abraçar. Quem?" },
  { id: 21, text: "Somos parte de um grupo de foragidos procurados no Velho Oeste. A cabeça de quem vale menos?" },
  { id: 22, text: "Precisamos de alguém para comandar as nossas tropas. Por favor, que não seja..." },
  { id: 23, text: "Se todos decidirmos virar comediantes, quem é o primeiro a morrer de fome?" },
  { id: 24, text: "Em futuro próximo, um de nós irá morrer sendo vítima de um acerto de contas. Quem?" },
  { id: 25, text: "Quem se acha mais inteligente do que realmente é?" },
  { id: 26, text: "Acordamos em uma ilha deserta e sem nenhum alimento. Quem irá propor canibalismo?" },
  { id: 27, text: "Qual de nós você jamais se atreveria a deixar irritado?" },
  { id: 28, text: "Estamos na prisão. Quem é o primeiro a se prostituir em troca de proteção?" },
  { id: 29, text: "Fomos convidados ao programa do Silvio. Quem discute com ele?" },
  { id: 30, text: "Quem se acha melhor do que os outros?" },
  { id: 31, text: "Vossa Majestade Infernal, também conhecido como Satanás, propõe realizar todos os nossos desejos em troca de nossas almas. Quem é o primeiro a aceitar?" },
  { id: 32, text: "Ganharemos mil dólares pra cada colher de merda que comermos. Quem está mais disposto a ser rico?" },
  { id: 33, text: "Quem pede o prato mais caro do cardápio e se faz de sonso na hora de dividir a conta?" },
  { id: 34, text: "Jamais encostaria na roupa íntima de..." },
  { id: 35, text: "O serviço militar agora é obrigatório para todos e todas. Quem é o primeiro a atirar no próprio pé para não servir?" },
  { id: 36, text: "Quem lê a Bíblia?" },
  { id: 37, text: "Todo grupo de amigos tem aquele que se veste muito mal. Em nosso grupo é..." },
  { id: 38, text: "Estamos no Apocalipse Zumbi! Quem é o primeiro a morrer?" },
  { id: 39, text: "Trabalhamos em um restaurante de fast food. Quem cospe na comida?" },
  { id: 40, text: "Um de nós é, na realidade, um robô. Quem?" },
  { id: 41, text: "Qual de nós você NÃO escolheria para adotar o seu filho?" },
  { id: 42, text: "\"Acho certo que o Brasil permita o casamento entre duas pessoas do mesmo gênero\" todos pensam, menos..." },
  { id: 43, text: "Quem peidou?" },
  { id: 44, text: "Quem convidaria um ex para tomar um café e mentiria descaradamente sobre sua vida atual?" },
  { id: 45, text: "Estamos participando de um reality show de talentos. Quem é eliminado no primeiro capítulo?" },
  { id: 46, text: "Um de nós tem uma coleção de chicletes mastigados pelo ex. Quem?" },
  { id: 47, text: "Um de nós não vê graça nesse jogo, mas está rindo apenas pra fingir que não é um cuzão. Quem?" },
  { id: 48, text: "Um de nós finge que está de boa, mas está secretamente ressentido pelo resultado de uma carta. Quem?" },
  { id: 49, text: "Descobriram a fórmula da imortalidade. Para o bem da humanidade, você esconde a fórmula de quem?" },
  { id: 50, text: "Um amigo em comum necessita de doação de sangue. Quem disse que doou, mas nem apareceu?" },
  { id: 51, text: "Um de nós gosta de sentir o próprio cheiro de chulé. Quem?" },
  { id: 52, text: "Estamos em um apocalipse nuclear. Quem roubaria os suprimentos de comida escondido?" },
  { id: 53, text: "Quem é o mais provável de esquecer o aniversário de todos?" },
  { id: 54, text: "Um de nós tem vergonha dos próprios pais. Quem?" },
  { id: 55, text: "Quem seria o primeiro a vender um amigo por dinheiro?" },
  { id: 56, text: "Quem já stalkeou o ex nas redes sociais usando conta fake?" },
  { id: 57, text: "Um de nós tem medo irracional de pombo. Quem?" },
  { id: 58, text: "Quem é o mais provável de dar bolo e inventar desculpa esfarrapada?" },
  { id: 59, text: "Quem trocaria um amigo por um influenciador famoso?" },
  { id: 60, text: "Um de nós ainda manda mensagem para \"crush\" que não responde. Quem?" },
  { id: 61, text: "Quem faria pacto com entidade sobrenatural em troca de fama?" },
  { id: 62, text: "Um de nós tem playlist secreta só com música brega. Quem?" },
  { id: 63, text: "Quem já fingiu não ver alguém na rua para não ter que cumprimentar?" },
  { id: 64, text: "Um de nós já chorou vendo comercial de TV. Quem?" },
  { id: 65, text: "Quem seria o primeiro a rir num velório em momento inadequado?" },
  { id: 66, text: "Um de nós tem coleção bizarra escondida em casa. Quem?" },
  { id: 67, text: "Quem é mais provável de virar coach picareta?" },
  { id: 68, text: "Um de nós já fuçou o celular de outra pessoa escondido. Quem?" },
  { id: 69, text: "Quem terminaria relacionamento por mensagem de texto?" },
  { id: 70, text: "Um de nós ainda sente ciúme de relacionamento antigo. Quem?" },
  { id: 71, text: "Quem toparia participar de experimento científico perigoso em troca de dinheiro?" },
  { id: 72, text: "Um de nós mente sobre quantas pessoas já beijou. Quem?" },
  { id: 73, text: "Quem inventaria fake news só para ver a confusão?" },
  { id: 74, text: "Um de nós marcaria casamento só para ganhar presente. Quem?" },
  { id: 75, text: "Quem seria o primeiro a abandonar o grupo no meio de um perrengue?" },
  { id: 76, text: "Um de nós já desejou o término do relacionamento de outra pessoa. Quem?" },
  { id: 77, text: "Quem toparia viver em reality show 24 horas por dia?" },
  { id: 78, text: "Um de nós guarda rancor por coisa pequena há anos. Quem?" },
  { id: 79, text: "Quem seria cancelado na internet em menos de uma semana?" },
  { id: 80, text: "Um de nós tem fantasias estranhas com professor(a) do passado. Quem?" },
  { id: 81, text: "Quem trocaria voto por favor pessoal?" },
  { id: 82, text: "Um de nós ainda conversa com \"contatinho\" enquanto está em relacionamento sério. Quem?" },
  { id: 83, text: "Quem é mais provável de inventar doença para faltar a compromisso?" },
  { id: 84, text: "Um de nós desligaria o Wi-Fi da casa inteira para ter paz. Quem?" },
  { id: 85, text: "Quem tem mais chance de ser preso por engano?" },
  { id: 86, text: "Um de nós já chorou no banho e nunca contou pra ninguém. Quem?" },
  { id: 87, text: "Quem finge que entende de vinho mas só toma suco de uva?" },
  { id: 88, text: "Um de nós ainda dorme de luz acesa. Quem?" },
  { id: 89, text: "Quem seria o primeiro a criar um perfil falso para stalkear o ex?" },
  { id: 90, text: "Um de nós tem uma tatuagem que se arrepende amargamente. Quem?" },
  { id: 91, text: "Quem iria para o BBB e sairia cancelado na primeira semana?" },
  { id: 92, text: "Um de nós acredita em signos e mapa astral. Quem?" },
  { id: 93, text: "Quem já comeu comida do lixo e nunca admitiu?" },
  { id: 94, text: "Um de nós deixaria o grupo no vácuo por dias de propósito. Quem?" },
  { id: 95, text: "Quem tem mais chance de virar meme sem querer?" },
  { id: 96, text: "Um de nós ainda usa a mesma senha para tudo desde 2010. Quem?" },
  { id: 97, text: "Quem seria o primeiro a cair em golpe do pix?" },
  { id: 98, text: "Um de nós já pagou por aplicativo de relacionamento. Quem?" },
  { id: 99, text: "Quem finge que está trabalhando mas está só scrollando o feed?" },
  { id: 100, text: "Um de nós tem medo de escuro e não assume. Quem?" },
  { id: 101, text: "Quem seria o primeiro a ser demitido por justa causa?" },
  { id: 102, text: "Um de nós já foi bloqueado por mais de 5 pessoas diferentes. Quem?" },
  { id: 103, text: "Quem tem mais chance de processar a própria família?" },
  { id: 104, text: "Um de nós guarda prints de conversas para usar como prova no futuro. Quem?" },
  { id: 105, text: "Quem já fez cosplay de personagem de anime em público?" },
  { id: 106, text: "Um de nós tem um diário secreto que ninguém pode ler. Quem?" },
  { id: 107, text: "Quem trocaria todos os amigos por uma vaga de estacionamento coberta?" },
  { id: 108, text: "Um de nós já fingiu ser outra pessoa na internet. Quem?" },
  { id: 109, text: "Quem seria o primeiro a chorar num filme infantil?" },
  { id: 110, text: "Um de nós tem uma pasta secreta no celular. Quem?" },
  { id: 111, text: "Quem já respondeu 'sim' sem ter entendido a pergunta?" },
  { id: 112, text: "Um de nós acha que canta bem mas desafina todo mundo. Quem?" },
  { id: 113, text: "Quem finge que gosta de acampar mas odeia mato?" },
  { id: 114, text: "Um de nós tem mais de 50 abas abertas no navegador agora. Quem?" },
  { id: 115, text: "Quem seria o primeiro a pedir comida no iFood escondido durante uma dieta em grupo?" },
  { id: 116, text: "Um de nós já pagou mico em festa de casamento. Quem?" },
  { id: 117, text: "Quem tem mais chance de esquecer o próprio aniversário?" },
  { id: 118, text: "Um de nós já fingiu ser vegetariano para impressionar alguém. Quem?" },
  { id: 119, text: "Quem deixaria o grupo no meio de um rolê para ir embora sem avisar?" },
  { id: 120, text: "Um de nós tem fotos comprometedoras que nunca foram apagadas. Quem?" },
  { id: 121, text: "Quem se acha influencer mas tem menos de 200 seguidores?" },
  { id: 122, text: "Um de nós já foi expulso de algum lugar público. Quem?" },
  { id: 123, text: "Quem tem mais chance de processar uma empresa de fast food?" },
  { id: 124, text: "Um de nós acha que é low profile mas só quer atenção. Quem?" },
  { id: 125, text: "Quem já devolveu presente de amigo oculto na loja?" },
  { id: 126, text: "Um de nós trocaria o grupo de amigos por um PlayStation 6. Quem?" },
  { id: 127, text: "Quem finge que sabe dançar mas faz sempre os mesmos passos?" },
  { id: 128, text: "Um de nós tem mais contas fake do que amigos reais. Quem?" },
  { id: 129, text: "Quem seria o primeiro a se mudar para outro país e nunca mais dar notícias?" },
  { id: 130, text: "Um de nós já mentiu no currículo e conseguiu o emprego. Quem?" },
  { id: 131, text: "Quem tem mais chance de ser expulso do grupo da família no WhatsApp?" },
  { id: 132, text: "Um de nós guarda nota fiscal de tudo, até de chiclete. Quem?" },
  { id: 133, text: "Quem já tomou banho de piscina de roupa e disse que 'foi sem querer'?" },
  { id: 134, text: "Um de nós seria capaz de vender a alma por um combo do McDonalds. Quem?" },
  { id: 135, text: "Quem já fingiu que o celular descarregou para não responder alguém?" },
  { id: 136, text: "Um de nós tem mais de 2000 fotos na galeria e nenhuma presta. Quem?" },
  { id: 137, text: "Quem seria o primeiro a cair em um prank de youtuber?" },
  { id: 138, text: "Um de nós já levou bronca de desconhecido na rua. Quem?" },
  { id: 139, text: "Quem tem a risada mais irritante do grupo?" },
  { id: 140, text: "Um de nós nunca lavou o copo da empresa e colocou de volta. Quem?" },
  { id: 141, text: "Quem seria o primeiro a chorar em uma DR de relacionamento?" },
  { id: 142, text: "Um de nós já fingiu ser rico em date e a conta veio no débito. Quem?" },
  { id: 143, text: "Quem já pediu dinheiro emprestado para o próprio filho?" },
  { id: 144, text: "Um de nós tem um podcast que ninguém ouve. Quem?" },
  { id: 145, text: "Quem mandaria um 'preciso falar com voce' e sumiria por horas?" },
  { id: 146, text: "Um de nós já foi bloqueado pela própria mãe no WhatsApp. Quem?" },
  { id: 147, text: "Quem tem mais chance de criar uma página de meme sem graça?" },
  { id: 148, text: "Um de nós aceitaria casar por conveniencia e depois pediria divórcio. Quem?" },
  { id: 149, text: "Quem já foi expulso de grupo de WhatsApp e voltou com outro número?" },
  { id: 150, text: "Um de nós não sabe usar liquidificador. Quem?" },
];
